// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryxcepqkvnywjrgqeqoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5eGNlcHFrdm55d2pyZ3FlcW9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMTc4OTksImV4cCI6MjA1ODU5Mzg5OX0.fhiBy_lw8etoRFSFboOAQ43CoEcKXl0juOs3LJwRHgY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);